---
- name: Enable Multiple Services
  hosts: test
  become: yes  # Run tasks with sudo

  tasks:
    - name: Start and enable Chronyd service
      service:
        name: chronyd
        state: started
      ignore_errors: yes  # Ignore errors if Chronyd is not installed or not stopped

    - name: Enable Chronyd service at boot
      systemd:
        name: chronyd
        enabled: yes
      ignore_errors: yes  # Ignore errors if Chronyd is not installed or not stopped

    - name: Start and enable Crond service
      service:
        name: crond
        state: started
      ignore_errors: yes  # Ignore errors if Crond is not installed or not stopped

    - name: Enable Crond service at boot
      systemd:
        name: crond
        enabled: yes
      ignore_errors: yes  # Ignore errors if Crond is not installed or not stopped

    - name: Start and enable Firewall service
      service:
        name: firewalld
        state: started
      ignore_errors: yes  # Ignore errors if Firewalld is not installed or not stopped

    - name: Enable Firewall service at boot
      systemd:
        name: firewalld
        enabled: yes
      ignore_errors: yes  # Ignore errors if Firewalld is not installed or not stopped
